### PR TITLE
NGINX dockerfile

### PR DESCRIPTION
**Pull request by rafkhan**

### CODE REVIEW

**Comment by igor-ka** [comment]
as far as i can see it looks good :+1:

**Comment by SethDavenport** [comment]
:shipit:

**Comment by SethDavenport** [comment]
@rafkhan what's happening with this PR?

**Comment by SethDavenport** [comment]
Closing due to inactivity.

**Comment by SethDavenport** [comment]
@rafkhan @bennett000 Is this still the approach we're talking for dockerizing the starters? If so I'll merge it & patch it over to the others; I just wanted to check first.

**Comment by SethDavenport** [comment]
@rafkhan @bennett000: ping

**Comment by SethDavenport** [comment]
Closing due to inactivity.

**Pull request closed without merging**
